# Generated by Django 6.0.6 on 2026-06-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('category', models.CharField(choices=[('sofa', 'Sofa'), ('bed', 'Bed'), ('dining', 'Dining'), ('wardrobe', 'Wardrobe'), ('tv-stand', 'TV Stand'), ('office', 'Office Furniture')], max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
